navikt/tilbakemeldinger

src/components/box/Box.less
src/components/box/Box.tsx
src/pages/kontakt-oss-frontpage/KontaktOss.tsx
src/pages/kontakt-oss-frontpage/sections/FAQ.less
src/pages/kontakt-oss-frontpage/sections/FAQ.tsx
src/pages/kontakt-oss-frontpage/sections/FAQLenker.ts
src/pages/kontakt-oss-frontpage/sections/FAQLenkerVisMer.tsx
src/pages/kontakt-oss-frontpage/sections/RingOss.tsx
src/pages/kontakt-oss-frontpage/sections/SkrivTilOss.tsx
src/pages/kontakt-oss-frontpage/sections/SkrivTilOssLenker.ts
src/pages/kontakt-oss-frontpage/sections/lenkepanel/LenkePanel.less
src/pages/kontakt-oss-frontpage/sections/lenkepanel/LenkePanelData.ts
src/pages/kontakt-oss-frontpage/sections/lenkepanel/linkbox/LinkBox.tsx
src/pages/tilbakemeldinger/Tilbakemeldinger.tsx

- Alle seksjoner og lenker er lagt inn iht skisser

Frontpage - Seksjoner og lenker

---

src/App.less
src/index.less

Overstyrer fokus-stil og fikser login/logout knapper som flyter ut

Css overstyringer

---

src/pages/skriv-til-oss/SkrivTilOssBase.tsx
src/pages/skriv-til-oss/SkrivTilOssLenkepanel.tsx
src/pages/skriv-til-oss/pages/SkrivTilOssForside.tsx

*Skilte ut skriv til oss lenkepaneler til egen komponent
*Endret lenker på disse til å bruke react router når mulig

Routing fixes

---

package-lock.json
package.json
src/assets/schema.json
src/language/nb.ts
src/pages/kontakt-oss-frontpage/KontaktOss.tsx
src/pages/skriv-til-oss/SkrivTilOssBase.tsx
src/pages/skriv-til-oss/pages/SkrivTilOssForside.tsx
src/pages/skriv-til-oss/pages/TemaArbeidssoker.tsx
src/pages/skriv-til-oss/pages/TemaFamilieOgBarn.tsx
src/pages/skriv-til-oss/pages/TemaHjelpemidler.tsx
src/pages/tilbakemeldinger/Tilbakemeldinger.tsx
src/pages/tilbakemeldinger/feil-og-mangler/FeilOgMangler.tsx
src/pages/tilbakemeldinger/ros-til-nav/Ros.tsx
src/pages/tilbakemeldinger/service-klage/ServiceKlage.tsx
src/types/modules.d.ts

- Legg til schema for kontaktinformasjon
- Legg til tittel og beskrivelse for alle sider

Forbedret SEO

---

src/Config.ts
src/language/nb.ts
src/pages/skriv-til-oss/pages/SkrivTilOssForside.tsx
src/pages/skriv-til-oss/pages/TemaFamilieOgBarn.tsx
src/pages/skriv-til-oss/pages/TemaHjelpemidler.tsx

*La til flere lenker på skriv til oss forside

---

src/Config.ts
src/language/nb.ts
src/pages/kontakt-oss-frontpage/KontaktOss.tsx
src/pages/skriv-til-oss/SkrivTilOssBase.tsx
src/pages/tilbakemeldinger/service-klage/ServicecKlageAnnenPerson.tsx

Dersom bruker velger "Nei jeg har ikke fullmakt" i serviceklage, skal det dukke opp en beskjed

Serviceklage

---

src/language/nb.ts
src/pages/kontakt-oss-frontpage/KontaktOss.less
src/pages/kontakt-oss-frontpage/KontaktOss.tsx

Oppdaterte tekster for chat-siden

Oppdatere tekster

---

src/App.tsx
src/Config.ts
src/Environments.ts
src/components/breadcrumbs/BreadcrumbsWrapper.tsx
src/pages/kontakt-oss-frontpage/KontaktOss.tsx

Endret forside path i prod til /person/kontakt-oss-ny uten redirect. /person/kontakt-oss skal fortsatt redirecte til gammel kontakt oss side.

Prod redirect endring

---

package-lock.json
package.json
src/language/nb.ts

Endret tekst på chat-knappen når chatten er stengt.
Samkjørt format for visning av tidsrom.

Tekst oppdateringer

---

package-lock.json
package.json
src/Config.ts
src/language/nb.ts
src/pages/chat/sider/ChatOkonomi.tsx

Denne chatten stenger 11.00 neste Onsdag.

Økonomi-chat spesiell åpningstid

---

package-lock.json
package.json
src/language/nb.ts

'Tilbakemeldinger' -> 'Tilbakemelding'

Tekstendring tilbakemeldinger

---

package-lock.json
package.json
src/pages/kontakt-oss-frontpage/sections/FAQLenker.ts

Flytter saksoversikt opp igjen

Faq lenke rekkefølge

---

package-lock.json
package.json
src/Config.ts
src/language/nb.ts
src/pages/kontakt-oss-frontpage/sections/FinnNavKontor.tsx

Lenker til mellomside med innlogget og uinnlogget løsning

Finn NAV-kontor lenker

---

package-lock.json
package.json
src/pages/skriv-til-oss/SkrivTilOss.less
src/pages/skriv-til-oss/sider/SkrivTilOssForside.tsx

Viser svartiden også på undersiden for skriv til oss

Skrivtiloss underside svartid

---

package-lock.json
package.json
src/Config.ts

Lenkefeil teknisk feil

---

package-lock.json
package.json
src/Config.ts
src/pages/chat/sider/ChatOkonomi.tsx

Økonomi chat stengt

---

package-lock.json
package.json
src/Config.ts
src/pages/chat/ChatTemasideBase.tsx
src/pages/chat/sider/ChatForside.tsx
src/utils/apningstider.ts

Chat skal stenges mellom 12:15-13:30 i dag

Stengt chat

---

package-lock.json
package.json
src/components/varsler/korona-virus-varsel/KoronaVirusVarsel.less

Gjør animasjonen litt mindre brekt i IE11

Korona varsel IE fix

---

package-lock.json
package.json
src/pages/chat/ChatTemaside.tsx

Starter chat-klienten umiddelbart med queryparameter "start"

Chat startparameter

---

package-lock.json
package.json
src/clients/apiMock/data/themes.json
src/components/lenkepanel/TemaLenkepanel.tsx
src/components/sanity-blocks/SanityBlocks.tsx
src/pages/chat/ChatForside.tsx
src/pages/chat/ChatTemaside.tsx
src/pages/kontakt-oss-frontpage/KanalVisning.tsx
src/pages/kontakt-oss-frontpage/KontaktOss.tsx
src/pages/skriv-til-oss/sider/SkrivTilOssForside.tsx
src/utils/sanity/endpoints/alert.tsx

Wrapper-komponent som setter serializeren og null-sjekker blocks-prop'en

Sanity blocks komponent

---

src/language/en.ts

Engelske tekster

---

.circleci/config.yml
package-lock.json
package.json

Fix for å muliggjøre deploy til prod når dev-deploy "feiler"

Deploy quickfix

---

package-lock.json
package.json
src/App.tsx
src/utils/locale.ts

Fikser språk-spesifikk logging av besøk

Språk-spesifikk pageview logging

---

package-lock.json
package.json
src/pages/chat/data/chatConfig.ts
src/pages/chat/data/chatTemasideData.ts

Chatbot for gjeldsrådgivning og ufør

---

package-lock.json
package.json
src/components/chatbot-wrapper/ChatbotUtils.ts
src/components/chatbot-wrapper/ChatbotWrapper.less
src/components/chatbot-wrapper/ChatbotWrapper.tsx
src/index.less
src/pages/chat/ChatTemaside.tsx
src/pages/chat/ChatbotTrigger.tsx
src/pages/chat/data/chatConfig.ts
src/pages/chat/data/chatTemasideData.ts

- Komponent for tydeligere chatbot funksjonalitet
- Fjerner release-flag for gjelds-chat

Chatbot wrapper

---

package-lock.json
package.json
src/language/en.ts
src/language/nb.ts
src/pages/chat/data/chatConfig.ts
src/pages/chat/data/chatTemasideData.ts

- Oppdatert tekst for kontakt veileder
- Fjerner flag for ufør chatbot-release

Kontakt veileder tekst

---

package-lock.json
package.json
src/components/chatbot-wrapper/ChatbotWrapper.less
src/components/chatbot-wrapper/ChatbotWrapper.tsx

Forhindrer at chatbot overlapper lenker i footer

Chatbot wrapper fix

---

package-lock.json
package.json
src/components/lenkepanel/TemaLenkepanel.tsx
src/pages/skriv-til-oss/skrivTilOssTemaLenker.ts
src/types/kanaler.ts

Muliggjør tema-paneler for temaer uten url. Fjerner url fra STO sosialhjelp.

Tema uten lenke

---

src/language/provider.ts
src/providers/Store.ts
src/types/sprak.ts
src/utils/locale.ts

Fikser feilmeldinger fra breadcrumbs ved første render når locale i url ikke er default-locale.

Breadcrumbs locale fix

---

package-lock.json
package.json
src/components/input-fields/EnhetCombobox.tsx
src/components/input-fields/InputMelding.tsx
src/components/input-fields/SelectEnhet.less
src/components/input-fields/SelectEnhet.tsx
src/components/sprakvelger/SprakVelger.less
src/components/sprakvelger/SprakVelger.tsx
src/index.less
src/language/en.ts
src/language/nb.ts
src/pages/tilbakemeldinger/ros-til-nav/Ros.less
src/pages/tilbakemeldinger/ros-til-nav/Ros.tsx
src/pages/tilbakemeldinger/service-klage/ServiceKlageBedrift.tsx

bytter ut react-select med downshift for select-bokser.
Gjelder språkvelger (skal ut i dekoratøren men bare har den med i pr'en for koden)
og selectboks for nav-enhet på siden for ros og serviceklage bedrift.
Noen ekstra endringer på språkvelger etter avtale med design for å forbedre uu.

Ny select komponent

---

.github/workflows/deploy.prod.yml
.github/workflows/deploy.q0.yml
.github/workflows/deploy.q1.yml
.github/workflows/deploy.q6.yml
package-lock.json
package.json

Fjerner bruk av deprecated set-env i github actions

Set env fix

---

src/Config.ts

Oppdaterer skriv til oss syk lenke

---

src/Config.ts

Oppdaterer lenker

---

.github/workflows/deploy.dev.yml
.github/workflows/deploy.prod.yml
.gitignore
.nais/config-dev.yaml
.nais/config-prod.yaml
.nais/config.yaml
navkontor-exceltiljson.js
package-lock.json
package.json
server/package-lock.json
server/package.json
server/server.js

Sjekker om url'ene for kontor-søket gir en ok-response, og logger feil dersom de ikke gjør det.

Periodisk sjekk på url'er for kontor-søk

---

src/language/en.ts
src/language/nb.ts

Issue #282. Teksten i forbindelse med "Pensjonist" er endret i Sanity.

Endring av teksten i CV-boksen. Erstattet med Bor og eller jobber.

---

src/language/en.ts
src/language/nb.ts
src/language/nn.ts

Endrer norsk, engelsk og nynorsktekst i lenke for klage.

Endre tekst i lenke for klage

---

public/index.html
src/components/lenkepanel/Lenkepanel.tsx
src/index.tsx
src/pages/tilbakemeldinger/feil-og-mangler/FeilOgMangler.tsx
src/pages/tilbakemeldinger/ros-til-nav/Ros.tsx
src/pages/tilbakemeldinger/service-klage/ServiceKlage.tsx

Diverse småforbedringer i forbindelse med wcag-rapport.

Forbedringer i forbindelse med UU

---

package-lock.json
package.json
src/App.tsx
src/index.tsx
src/pages/tilbakemeldinger/service-klage/login-modal/LoginModal.tsx

Fiks LoginModal
Eks: Har testet selv i dev

UU-fiks LoginModal 

---

.github/workflows/deploy.dev-gcp.yml
.github/workflows/deploy.prod-gcp.yml
package-lock.json
package.json
src/App.tsx
src/components/metatags/MetaTags.tsx
src/pages/404/404.tsx
src/types/modules.d.ts

Eks:
-  Byttet ut react-meta-tags med react-helmet-async
Har testet lokalt
Usikker på om alle link-tagene i MetaTags-komponenten er nødvendige. Tenker å ta en prat med Tobias om dette.

Byttet ut react-meta-tags med react-helmet-async

---

.github/workflows/deploy.prod-gcp.yml

Oppdatert deploy-prod-workflow til å pushe til CDN

---

.nais/config-dev.yaml
.nais/config-prod.yaml
server/server.ts
src/App.tsx
src/Environments.ts

Loginservice -> Wonderwall
Idporten-sidecar på enables for at auth-header skal populeres slik at vi kan hente ut tokenet på serversiden.

Loginservice -> Wonderwall

---

package-lock.json
package.json
src/components/input-fields/EnhetCombobox.tsx
src/components/input-fields/SelectEnhet.tsx
src/pages/tilbakemeldinger/service-klage/ServiceKlage.tsx

Oppdatert dependencies. 
Tar i bruk aksel-icons.
Beholder node 18
Har testet selv i dev

Dependencies 202306

---

docker-compose.yml

Fjerner ubrukt Unleash-referanse i environment

Fjerner ubrukt unleash-referanse

---

src/App.tsx

Endrer redirects til /nb/* slik at den replacer forrige entry i history stacken

Replace for redirects

---

package-lock.json
package.json
src/App.scss

- Bumper Aksel
Har tetstet selv i dev

Sikrer nok kontrast og fjerner kursiv på counter TextArea

---

.github/workflows/deploy.dev-gcp.yml
.github/workflows/deploy.prod-gcp.yml

Fjerner deploy key etter at nais har begynt å støtte authentication under panseret.
Testet i dev

Fjerne deploy key

---

.nais/config.yml
package-lock.json
server/package.json
server/src/api/setupApiRoutes.ts
server/src/server.ts

Rate limiting
